public without sharing class DXUtilities {
    // THIS IS ME
    
    // THIS SHOULD BE A SIMPLE MERGE
    
    public String utility1 {get;set;}
    
    public DXUtilities() {
        utility1 = 'This is a String variable';
    }
    
    public void DXUtilities2() {
        utility1 = 'This is a String variable 2';
    }
    
    
    
    
    public void DXUtilities3() {
        utility1 = 'This is a String variable 3';
    }
    
    public void DXUtilities4() {
        utility1 = 'This should be a conflict';
    }
    
    public void DXUtilities5() {
        utility1 = 'This is a String variable 5';
    }
    
    
    
    
    public void DXUtilities6() {
        utility1 = 'This is a String variable 6';
    }
    public void DXUtilities7() {
        utility1 = 'This is should be a second conflict';
    }
    
    
    
    
    public void DXUtilities8() {
        utility1 = 'This is a String variable 8';
        
        // THIS SHOULD BE A SIMPLE MERGE
    }
}